- name: Initial VPN server configuration
  hosts: all
  become: true
  collections:
    - pgalonza.linux
  roles:
    - prepare
  vars_files:
    - ./project-vars.yml
  pre_tasks:
    - name: Disable Firewalld
      ansible.builtin.systemd:
        state: stopped
        name: firewalld
        enabled: false
