- name: Initial VPN server configuration
  hosts: all
  become: true
  collections:
    - pgalonza.linux
  roles:
    - docker
    - security
  vars:
    vpn_user: "{{ lookup('env', 'VPN_USER') }}"
    sshd_port: "{{ lookup('env', 'SSHD_PORT') }}"
    ssh_key_dir: ~/.ssh
    ansible_user: urahara
    sshd_allow_users:
      - "{{ vpn_user }}"
      - "{{ ansible_user }}"
    nftables_allowed_tcp_dports":
      - "{{ sshd_port }}"
    nftables_allowed_udp_dports: []
  tasks:
    - name: Generate an OpenSSH keypair
      become: false
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_dir }}/{{ vpn_user }}_id_rsa"
        type: ed25519
      delegate_to: localhost
      run_once: true
    - name: Add sudo group
      ansible.builtin.group:
        name: sudo
        state: present
        system: true
    - name: Add the VPN user
      ansible.builtin.user:
        name: "{{ vpn_user }}"
        comment: VPN user
        create_home: true
        shell: /bin/bash
        system: true
        groups:
          - sudo
          - docker
    - name: Install VPN user ssh key
      ansible.posix.authorized_key:
        user: "{{ vpn_user }}"
        state: present
        key: "{{ lookup('file', '{{ ssh_key_dir }}/{{ vpn_user }}_id_rsa.pub') }}"
    - name: "VPN user permissions"
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ vpn_user }}"
        content: "{{ vpn_user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0600"
        validate: "/usr/sbin/visudo --check --file=%s"
    # - name: VPN user permissions
    #   community.general.sudoers:
    #     name: "{{ vpn_user }}"
    #     host: ALL
    #     commands: ALL
    #     noexec: false
    #     nopassword: true
    #     user: "{{ vpn_user }}"
