---
# =============================================================================
# Playbook: VPN server audit
# =============================================================================
# Checks the server configuration against security best practices.
# =============================================================================
- name: VPN server audit
  hosts: all
  become: true
  collections:
    - pgalonza.linux
  roles:
    - audit
  vars_files:
    - ../vars/project-vars.yml
